### ISSUE TITLE
duplicate URLs in reading order and resource list

### ISSUE THREAD

**Issue by dauwhe** [w3c/pub-manifest#138] opened 2019-10-25 13:53 UTC
Our spec says

> Note that a particular resource's URL MUST NOT appear in more than one of these lists, and a URL MUST NOT be repeated within a list.

I can at least imagine content that involves repetition. Poems may have repeated stanzas. It's not impossible to imagine experimental fiction where long sections of content may be repeated. It feels like we are legislating against errors here, but in a way that restricts the freedom of authors. Perhaps this is worthy of discussion? 

This could especially become an issue with profiles where the reading order consists of images or audio.

**Comment by iherman** [comment] 2019-10-25 14:19
Actually... your example violates another restriction in the current spec: 

> The URLs expressed in the reading order MUST NOT include fragment identifiers.

(I presume you would use a fragment identifier to point to stanzas...)

To be honest, I do not know where these restrictions come from.

**Comment by dauwhe** [comment] 2019-10-25 14:38
> (I presume you would use a fragment identifier to point to stanzas...)

Not necessarily. If the repetition were hundreds of lines it might be a separate file. But now we are asking authors to divide up their content only in certain ways. 

Once again we hit a fundamental philosophical difference between EPUB and the web. With EPUB we help authors avoid errors. The web allows authors immense freedom to make mistakes. 

Should web publications be like EPUB, or be like the web?

**Comment by mattgarrish** [comment] 2019-10-25 22:40
But how would you reuse the exact same file in a sequence of pages on the web and still direct the user to the correct previous/next page? Hope you get a meaningful referrer?

I believe the problem is the same for reading systems, as where exactly is the reader if the same file is defined at multiple positions? There will be pathways and situations (resumption) that will complicate knowing the context of the file.

That's my recollection of how we came to this restriction, although I haven't been able to track down where it was discussed.

**Comment by mattgarrish** [comment] 2019-10-28 17:48
> Note that a particular resource's URL MUST NOT appear in more than one of these lists

This part I can get behind reducing to a should, or even dropping. What does it matter if a resource is listed in both when you have to get a union to find the unique list of resources? What breaks by having a resource declared in both lists? It's convenient not to have to list in both, but that shouldn't prevent someone from being super detailed...

Or, put differently, why bother saying it's a union when by definition you should only have to join the lists if you can't repeat resources (doing a union would only matter for error checking).

**Comment by dauwhe** [comment] 2019-10-28 17:53
> What does it matter if a resource is listed in both when you have to get a union to find the unique list of resources? What breaks by having a resource declared in both lists?

Yes. It feels like we're focusing a bit on theoretical purity, rather than being as minimally restrictive as possible while still creating a spec that's implementable.

**Comment by mattgarrish** [comment] 2019-10-28 18:01
I think this statement is a bit worthless as far as normative statements go, too:

> The completeness of the resource list can affect the usability of a digital publication in certain reading scenarios (e.g., the ability to read it offline). For this reason, it is strongly RECOMMENDED to provide a comprehensive list of all of the publication's constituent resources beyond those listed in the default reading order.

"strongly advised", yes, but otherwise what sort of checking is this supposed to entail? I'm not writing an algorithm to hunt for possible missed "comprehensive" resources... :)

**Comment by mattgarrish** [comment] 2019-10-29 11:46
To try and address all the issues, how about this as a resolution:

- we delete the requirement that a URL not appear more than once in a list as a general rule (this also seems problematic for the links section)
- for the reading order:
  - to avoid rendering ambiguities, resources should not be listed more than once in the default reading order (i.e., we warn but don't strip duplicates) - if we hear duplication causes no issues for user agents, we can always reduce this further
  - fragment identifiers should not be included in the default reading order, but if they are we warn about them and strip them during processing
- for the resource list:
  - to avoid conflicting information, resources should not be listed more than once -if they are, only the first instance is retained during processing
  - fragment identifiers should not be included, but like reading order we warn and strip

**Comment by mattgarrish** [comment] 2019-10-29 11:50
Also:

- if a resource has already been declared in the reading order, any subsequent declaration(s) in the resource list are quietly ignored when compiling the list of resources in the bounds

**Comment by iherman** [comment] 2019-10-29 12:32
That works for me.

**Comment by HadrienGardeur** [comment] 2019-10-30 16:43
From a UA perspective:

- duplicated resources in the resource list is sub-optimal but not a major issue
- duplicated resources in the reading order would cause major headaches

Let's say that a resource is present twice in the reading order. The first time at 20% of the book, the second time at 80% of the book. 
When I follow a link to that resource, should I consider that this is for the first or second resource?

**Comment by mattgarrish** [comment] 2019-10-30 18:39
> When I follow a link to that resource, should I consider that this is for the first or second resource?

Yes, I'm personally more comfortable leaving that particular restriction in place. Even in an audio format it seems flawed, as links from a table of contents could introduce this confusion. I'm going to un-strike that and see where the discussion Monday leads on this.

**Comment by dauwhe** [comment] 2019-11-04 14:32
> Yes, I'm personally more comfortable leaving that particular restriction in place. Even in an audio format it seems flawed, as links from a table of contents could introduce this confusion. I'm going to un-strike that and see where the discussion Monday leads on this.

I think the TOC case is solvable, with some programming, but the arbitrary link problem is more difficult. I'm OK with keeping the restriction.

**Comment by mattgarrish** [comment] 2019-11-04 14:54
> I think the TOC case is solvable, with some programming, but the arbitrary link problem is more difficult.

It's the pathway to EPUB CFI to make both reliable, but let's not go there...

**Comment by iherman** [comment] 2019-11-05 08:48
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-11-04-pwg#section1-1).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Garth Conboy: <a href="https://github.com/w3c/pub-manifest/issues/138">https://github.com/w3c/pub-manifest/issues/138</a><br/>
Garth Conboy: <a href="https://github.com/w3c/pub-manifest/pull/131">https://github.com/w3c/pub-manifest/pull/131</a> (corresponding PR)<br/>
Matt Garrish: a number of issues came up last week… dauwhe had raised a couple of questions… going through algo to implement the spec<br/>
… the major ones in 138 are that we’re not going to have a MUST NOT on fragment ids on manifest level, but could be restricted at the profile level<br/>
… the other one (PR 131) also deals with publication of resources in reading order and resource list<br/>
… we had “MUST NOT” but we will leave it at “SHOULD NOT”… if it’s there, we won’t mess around with your reading order<br/>
… strongly advised that you don’t declare resources multiple times in reading order… leads to ambiguity<br/>
… we want to generally avoid that issue<br/>
… other than that, the changes were mostly editorial cleanup<br/>
… to recap: fragment ids are allowed, and you can declare multiple resources, and it will be a warning (still)<br/>
… we can discuss the resource issues now… i don’t think we need to restrict fragment ids at the publication level<br/>
Garth Conboy: nobody on the queue… ivan made an off comment on alternate issues… what did you mean?<br/>
Ivan Herman: we also had an issue in the last few days on what happens if you provide an alternate [?]<br/>
Matt Garrish: choosing alternates is issue 133… separate from 138<br/>
Garth Conboy: let’s stick with 138 for the moment<br/>
… nobody on the queue… dauwhe, you had chimed in on this issue. are you happy with where we are?<br/>
Dave Cramer: yes, i think allowing fragment ids is important, but i’m fine with the decision on duplicate resources… when we make restrictions I want us to be very conscious about what we’re restricting and why<br/>
</details>

**Comment by iherman** [comment] 2019-11-05 08:48
@mattgarrish can this be closed now?

**Comment by iherman** [comment] 2019-11-05 08:49
(The corresponding PR, i.e. #131, has been merged...)

**Closed** 2019-11-05 14:03 UTC
Labels: propose closing
