### ISSUE TITLE
Inclusion of certifiedBy, conformsTo and certifiersCredential

### ISSUE THREAD

**Issue by clapierre** [w3c/pub-manifest#73] opened 2019-09-18 20:35 UTC
We specifically added the optional
accessibility-report in 2.8.1.1 Accessibility Report

I would propose including
accessibility-conformsTo
accessibility-certifiedBy
and
accessibility-certifiersCredential

Since these are metadata properties being added to conformant EPUBs currently in the US.  Macmillan Learning for one is publishing EPUBs with this information and being able to include it in a web manifest I would think would be equally important.
Self Certification is also possible and Pearson I believe is already doing this as well.

**Comment by mattgarrish** [comment] 2019-09-18 20:51
`conformsTo` is a property in `dcterms` so it can already be used without needing to do anything special (the prefix is declared in the schema.org context file).

The others can be used by extending the context:

```
{
    {
    "@context" : [
        "https://schema.org",
        "https://www.w3.org/ns/pub-context",
        {"a11y": "http://www.idpf.org/epub/vocab/package/a11y/#"}
    ],
    …
    "a11y:certifiedBy" : "Benetech",
    "a11y:certifierCredential" : "GCA",
    …
}
```

This might be a better example of extending the manifest than the fake prefix declaration I hastily added the other day.

**Comment by iherman** [comment] 2019-09-18 21:26
If these are widely used (you guys tell me) we can also put the

```
{"a11y": "http://www.idpf.org/epub/vocab/package/a11y/#"}
```

into `pub-context`, i.e., the extra context definition becomes unnecessary.

**Comment by mattgarrish** [comment] 2019-09-18 23:56
It's used for EPUB, but in the absence of web publications, I'm not sure what usage the properties will receive for audiobooks. Might be something to standardize later.

**Comment by mattgarrish** [comment] 2019-09-24 00:05
I'm now leaning toward doing nothing with this one for the present.

When we created the EPUB vocabulary it was intended to be a workaround to not having the time to go through a standardization process like would be required to get them in schema.org. Eventually we should take this issue up again, especially if we want to use the properties outside of EPUB. Defining them in every format that might need them is not a good long-term approach.

Without knowing what the future of the properties is, though, and without knowing if they'll be used for audiobooks, we should probably wait on any solution. The context can be updated any time, I believe, so there's no problem waiting until we know more. And you can always extend to add the properties now, but we don't need to code it into the specification if the vocabulary and expressions might change in the near future.

**Comment by mattgarrish** [comment] 2019-09-30 16:37
I propose we close this issue. @clapierre figuring out the future of the vocabulary is an issue you should open with the epub cg.

**Comment by clapierre** [comment] 2019-09-30 17:05
I am fine with that, and yes we can bring this up with the CG and possibly recommend adding these to Schema.org

**Closed** 2019-09-30 17:11 UTC
